version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finanza-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: finanzanewsdb
      MYSQL_USER: finanza_user
      MYSQL_PASSWORD: t4tt01987
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: finanza-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/finanzanewsdb
      SPRING_DATASOURCE_USERNAME: finanza_user
      SPRING_DATASOURCE_PASSWORD: t4tt01987
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: finanza-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8080

volumes:
  mysql_data:
    driver: local
